[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
futures-util = "0.3"
reqwest = "0.12"
reqwest-websocket = "0.5"
tokio = { version = "1.47", features = ["io-std", "macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
