[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws"] }
futures-util = "0.3"
tokio = { version = "1.47", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.3"
